CREATE DATABASE VERANUM;
USE VERANUM;

CREATE TABLE EMPRESA (
    RUT         INT PRIMARY KEY,
    NOMBRE      VARCHAR(255) NOT NULL,
    DIRECCION   VARCHAR(255) NOT NULL,
    TELEFONO    VARCHAR(12) NOT NULL,
    ESTADO      INT NOT NULL /*1) ACTIVO 2) INACTIVO*/
);

CREATE TABLE USUARIO (
    RUT             INT PRIMARY KEY,
    NOMBRE          VARCHAR(70) NOT NULL,
    APELLIDO        VARCHAR(70) NOT NULL,
    TELEFONO        VARCHAR(12) NOT NULL,
    DIRECCION       VARCHAR(255),
    CORREO          VARCHAR(255),
    TIPO            INT NOT NULL,  /*1) normal 4) admin 5) super admin*/
    ESTADO          INT NOT NULL,  /*1) ACTIVO 2) INACTIVO*/
    NOMBREUSUARIO   VARCHAR(50) NOT NULL,
    CONTRASENA      VARCHAR(50) NOT NULL,
    EMPRESAID       INT,
    CONSTRAINT FK_USUARIO_EMPRESA FOREIGN KEY (EMPRESAID) REFERENCES EMPRESA(RUT)
);

CREATE TABLE HOTEL (
    ID              INT AUTO_INCREMENT PRIMARY KEY,
    DIRECCION       VARCHAR(255) NOT NULL,
    REGION          VARCHAR(255) NOT NULL,
    TELEFONO        VARCHAR(12) NOT NULL,
    ESTADO          INT NOT NULL, /*1) ACTIVO 2) INACTIVO*/
    ADMINISTRADOR   INT,
    CONSTRAINT FK_HOTEL_USUARIO FOREIGN KEY (ADMINISTRADOR) REFERENCES USUARIO(RUT)
);

CREATE TABLE PRODUCTO (
    ID                  INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE              VARCHAR(70) NOT NULL,
    DESCRIPCION         VARCHAR(255),
    STOCK_TOTAL         INT NOT NULL,
    STOCK_DISPONIBLE    INT NOT NULL,
    UBICACION           VARCHAR(255),
    ESTADO              INT NOT NULL, /*1) ACTIVO 2) INACTIVO*/
    HOTELID             INT NOT NULL,
    CONSTRAINT FK_PRODUCTO_HOTEL FOREIGN KEY (HOTELID) REFERENCES HOTEL(ID)
);

CREATE TABLE SERVICIO (
    ID              INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE          VARCHAR(70) NOT NULL,
    DESCRIPCION     VARCHAR(255) NOT NULL,
    ESTADO          INT NOT NULL, /*1) ACTIVO 2) INACTIVO*/
    HOTELID         INT NOT NULL,
    CONSTRAINT FK_SERVICIO_HOTEL FOREIGN KEY (HOTELID) REFERENCES HOTEL(ID)
);

CREATE TABLE HABITACION (
    ID              INT AUTO_INCREMENT PRIMARY KEY,
    NUMERO          VARCHAR(10) NOT NULL,
    CAMAS           INT NOT NULL,
    CAPACIDAD       INT NOT NULL,
    BANOS           INT NOT NULL,
    ESTADO          INT NOT NULL, /*1) ACTIVO 2) INACTIVO*/
    HOTELID         INT NOT NULL,
    CONSTRAINT FK_HABITACION_HOTEL FOREIGN KEY (HOTELID) REFERENCES HOTEL(ID)
);

CREATE TABLE PROMOCION (
    ID              INT AUTO_INCREMENT PRIMARY KEY,
    FECHA           DATE NOT NULL,
    PRECIO          INT NOT NULL,
    ESTADO          INT NOT NULL, /*1) ACTIVO 2) INACTIVO*/
    HABITACIONID    INT NOT NULL,
    CONSTRAINT FK_PROMOCION_HABITACION FOREIGN KEY (HABITACIONID) REFERENCES HABITACION(ID)
);

CREATE TABLE PRECIODIA (
    ID              INT AUTO_INCREMENT PRIMARY KEY,
    FECHA           DATE NOT NULL,
    PRECIO          INT NOT NULL,
    HABITACIONID    INT NOT NULL,
    CONSTRAINT FK_PRECIODIA_HABITACION FOREIGN KEY (HABITACIONID) REFERENCES HABITACION(ID)
);

CREATE TABLE RESERVA (
    ID              INT AUTO_INCREMENT PRIMARY KEY,
    FECHA_INICIO    DATE NOT NULL,
    FECHA_TERMINO   DATE NOT NULL,
    TOTAL           INT NOT NULL,
    MEDIO_PAGO      INT NOT NULL, /*1) EFECTIVO 2) TARJETA*/
    ESTADO          INT NOT NULL, /*1) NORMAL 2) NULA*/
    HABITACIONID    INT NOT NULL,
    USUARIOID       INT NOT NULL,
    CONSTRAINT FK_RESERVA_HABITACION FOREIGN KEY (HABITACIONID) REFERENCES HABITACION(ID),
    CONSTRAINT FK_RESERVA_USUARIO FOREIGN KEY (USUARIOID) REFERENCES USUARIO(RUT)
);
